INSERT INTO "rnd_loops" (
	"id",
	"theme",
	"question",
	"hypothesis",
	"notes",
	"status",
	"priority",
	"owner_agent_id",
	"cadence",
	"source",
	"position",
	"metadata"
) VALUES
	(
		'rnd-heartbeat-work-selection',
		'Heartbeat work selection',
		'What should a heartbeat do when there is no urgent inbox/calendar/mail signal?',
		'Heartbeats should advance one safe queued task or R&D loop before returning HEARTBEAT_OK.',
		'Investigate heartbeat-state, dispatch summary, and recent idle behavior.',
		'backlog',
		88,
		(select id from "agents" where id = 'cai'),
		'weekly',
		'migration-seed',
		4000,
		'{"seeded": true, "area": "autonomy"}'::jsonb
	),
	(
		'rnd-task-capture-classification',
		'Task capture and classification',
		'How should loose Telegram ideas become structured tasks without Felipe manually restating them?',
		'Agent OS needs an intake layer that classifies ideas into task, R&D loop, memory, blocker, or parked.',
		'Compare Telegram context, Action Center, task APIs, and Life OS capture patterns.',
		'backlog',
		85,
		(select id from "agents" where id = 'cai'),
		'weekly',
		'migration-seed',
		5000,
		'{"seeded": true, "area": "intake"}'::jsonb
	),
	(
		'rnd-agent-evals-feedback',
		'Agent evals and feedback loops',
		'How do we know Cai and Charles are getting more useful instead of just doing more activity?',
		'Small behavioral evals can catch regressions in proactivity, tool use, task choice, and follow-through.',
		'Inspect current evals, proactivity harness, and recurring failure modes from memory.',
		'backlog',
		82,
		(select id from "agents" where id = 'cai'),
		'biweekly',
		'migration-seed',
		6000,
		'{"seeded": true, "area": "quality"}'::jsonb
	),
	(
		'rnd-knowledge-memory-maintenance',
		'Knowledge and memory maintenance',
		'What should be distilled from raw daily memory into durable memory, docs, or tasks?',
		'Regular memory review should produce fewer stale notes and better future context.',
		'Test a heartbeat-safe review that promotes only decisions, preferences, and recurring blockers.',
		'backlog',
		78,
		(select id from "agents" where id = 'cai'),
		'weekly',
		'migration-seed',
		7000,
		'{"seeded": true, "area": "memory"}'::jsonb
	),
	(
		'rnd-external-agent-research',
		'External agent research radar',
		'What are other agent systems doing that Agent OS should steal, adapt, or reject?',
		'Useful external patterns should become small experiments, not passive reading notes.',
		'Track loops, task queues, memory, evals, permissions, and UI affordances from current agent products.',
		'backlog',
		76,
		(select id from "agents" where id = 'cai'),
		'weekly',
		'migration-seed',
		8000,
		'{"seeded": true, "area": "research"}'::jsonb
	),
	(
		'rnd-taskflow-handoff-model',
		'TaskFlow handoff model',
		'When should Cai do work directly, spawn a subagent, use TaskFlow, or create a permanent agent?',
		'Clear handoff rules will reduce half-finished detached work and make broad work safer.',
		'Use OPERATIONS.md, TaskFlow docs, and recent agent work as test cases.',
		'backlog',
		74,
		(select id from "agents" where id = 'cai'),
		'biweekly',
		'migration-seed',
		9000,
		'{"seeded": true, "area": "operating-model"}'::jsonb
	),
	(
		'rnd-agent-os-observability',
		'Agent OS observability',
		'What should Felipe see to trust that agents are working without being nagged?',
		'The dashboard needs concise evidence of useful work: picked tasks, blocked tasks, shipped changes, and next actions.',
		'Investigate dispatch summaries, build activity, notifications, and R&D loop status as one cockpit surface.',
		'backlog',
		72,
		(select id from "agents" where id = 'cai'),
		'weekly',
		'migration-seed',
		10000,
		'{"seeded": true, "area": "dashboard"}'::jsonb
	),
	(
		'rnd-autonomy-permissions-policy',
		'Autonomy permissions policy',
		'Which actions can agents take without asking, which require approval, and which are blocked?',
		'Agent OS needs explicit autonomy levels per task type so agents can move without creating risk.',
		'Turn workspace red lines and operating conventions into machine-readable task policy.',
		'backlog',
		70,
		(select id from "agents" where id = 'cai'),
		'monthly',
		'migration-seed',
		11000,
		'{"seeded": true, "area": "safety"}'::jsonb
	)
ON CONFLICT ("id") DO NOTHING;
