import Link from 'next/link';
import { Badge } from '@/components/ui/badge';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Icons } from '@/components/icons';
import type { QaReport, QaStrategyDefinition } from '../api/types';

interface QaCustomerPageProps {
  customerName: string;
  customerSlug: string;
  strategy: QaStrategyDefinition;
  reports: QaReport[];
}

export function QaCustomerPage({
  customerName,
  customerSlug,
  strategy,
  reports
}: QaCustomerPageProps) {
  return (
    <main className='bg-background min-h-screen'>
      <section className='border-b'>
        <div className='mx-auto max-w-7xl px-4 py-12 sm:px-6 lg:px-8 lg:py-16'>
          <Link
            href={`/qa-rapport/${strategy.vertical}`}
            className='text-muted-foreground hover:text-foreground inline-flex items-center gap-2 text-sm font-medium'
          >
            <Icons.chevronLeft className='size-4' />
            {strategy.name}
          </Link>
          <div className='mt-8 max-w-4xl'>
            <div className='flex flex-wrap gap-2'>
              <Badge variant='secondary'>{strategy.shortName}</Badge>
              <Badge variant='outline'>{customerSlug}</Badge>
            </div>
            <h1 className='text-foreground mt-5 text-4xl font-semibold tracking-tight sm:text-5xl'>
              {customerName} QA reports
            </h1>
            <p className='text-muted-foreground mt-5 max-w-3xl text-lg leading-8'>
              Public {strategy.shortName} reports generated by Sladdis for this customer.
            </p>
          </div>
        </div>
      </section>

      <section className='mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8'>
        <Card className='rounded-lg'>
          <CardHeader>
            <CardTitle>Reports</CardTitle>
            <CardDescription>
              Share report links from this page when a customer has multiple test runs.
            </CardDescription>
          </CardHeader>
          <CardContent className='grid gap-4 md:grid-cols-2'>
            {reports.map((report) => (
              <Link
                key={report.slug}
                href={`/qa-rapport/${report.vertical}/${report.customerSlug}/${report.slug}`}
              >
                <div className='hover:bg-muted/50 h-full rounded-md border p-4 transition-colors'>
                  <div className='flex items-start justify-between gap-4'>
                    <div>
                      <div className='font-medium'>{report.title}</div>
                      <p className='text-muted-foreground mt-2 text-sm leading-6'>
                        {report.verdict}
                      </p>
                    </div>
                    <Badge variant='outline'>{report.score}/100</Badge>
                  </div>
                  <div className='text-muted-foreground mt-4 font-mono text-xs'>
                    /qa-rapport/{report.vertical}/{report.customerSlug}/{report.slug}
                  </div>
                </div>
              </Link>
            ))}
          </CardContent>
        </Card>
      </section>
    </main>
  );
}
