import {
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowRight,
  IconBell,
  IconBold,
  IconBolt,
  IconBox,
  IconBrain,
  IconBrandGithub,
  IconBrandBinance,
  IconBrandTwitter,
  IconBrandVercel,
  IconBrightness,
  IconBulb,
  IconCalendar,
  IconCalendarEvent,
  IconCalendarStats,
  IconCash,
  IconChartBar,
  IconChartCandle,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCircleDot,
  IconCirclePlus,
  IconCircleX,
  IconClipboardText,
  IconClock,
  IconCloud,
  IconCode,
  IconCommand,
  IconCopy,
  IconCpu,
  IconCreditCard,
  IconDeviceLaptop,
  IconDatabase,
  IconDatabaseSearch,
  IconDots,
  IconDotsVertical,
  IconEdit,
  IconExternalLink,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileZip,
  IconFilter,
  IconFolder,
  IconGripVertical,
  IconHelpCircle,
  IconGitBranch,
  IconInbox,
  IconInfoCircle,
  IconItalic,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLibrary,
  IconLink,
  IconListCheck,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconMail,
  IconMessage,
  IconMessageCircle,
  IconMinus,
  IconMoon,
  IconMusic,
  IconNetwork,
  IconNews,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlayerPlay,
  IconPlus,
  IconProps,
  IconRosetteDiscountCheck,
  IconRobot,
  IconRocket,
  IconSearch,
  IconSelector,
  IconSend,
  IconSettings,
  IconShare,
  IconShield,
  IconShieldCheck,
  IconSlash,
  IconSparkles,
  IconStack2,
  IconStar,
  IconSun,
  IconTerminal2,
  IconTargetArrow,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconWallet,
  IconWorld,
  IconTimeline,
  IconCrown,
  IconX
} from '@tabler/icons-react';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  brain: IconBrain,
  bulb: IconBulb,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  circleDot: IconCircleDot,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  command: IconCommand,
  copy: IconCopy,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  filter: IconFilter,
  link: IconLink,
  library: IconLibrary,
  target: IconTargetArrow,
  timeline: IconTimeline,
  zap: IconBolt,

  // Navigation / Chevrons
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,

  // Layout
  activity: IconActivity,
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  network: IconNetwork,
  panelLeft: IconLayoutSidebar,
  terminal: IconTerminal2,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  binance: IconBrandBinance,
  twitter: IconBrandTwitter,
  vercel: IconBrandVercel,
  logo: IconCommand,

  // Communication
  chat: IconMessage,
  messageCircle: IconMessageCircle,
  inbox: IconInbox,
  mail: IconMail,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  play: IconPlayerPlay,
  rocket: IconRocket,
  upload: IconUpload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  cash: IconCash,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Data / Charts
  calendarStats: IconCalendarStats,
  chartBar: IconChartBar,
  chartCandle: IconChartCandle,
  database: IconDatabase,
  databaseSearch: IconDatabaseSearch,
  gitBranch: IconGitBranch,
  globe: IconWorld,
  news: IconNews,
  listChecks: IconListCheck,
  shield: IconShield,
  shieldCheck: IconShieldCheck,
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  eyeOff: IconEyeOff,
  adjustments: IconAdjustmentsHorizontal,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  bot: IconRobot,
  calendarDays: IconCalendarEvent,
  cloudSun: IconCloud,
  cpu: IconCpu,
  pizza: IconPizza,
  wallet: IconWallet,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots
};
